services:
  prometheus:
    image: prom/prometheus:v3.3.1
    user: "0:0"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - /mnt/cephfs/prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=60d"
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
  blackbox:
    image: prom/blackbox-exporter:v0.27.0
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    ports:
      - "9115:9115"
    configs:
      - source: blackbox_config
        target: /etc/blackbox/blackbox.yml
configs:
  prometheus_config:
    file: ./prometheus.yml
  blackbox_config:
    file: ./blackbox.yml