global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'proxmox_graphite_exporter'
    metrics_path: "/metrics"
    dns_sd_configs:
      - names:
          - "_graphite-exporter._tcp.twop.ch"
        type: SRV
        refresh_interval: 30s

  - job_name: 'proxmox_node_exporter'
    metrics_path: "/metrics"
    dns_sd_configs:
    - names:
        - "_node-exporter._tcp.twop.ch"
      type: SRV
      refresh_interval: 30s
  - job_name: 'ceph_exporter'
    metrics_path: "/metrics"
    dns_sd_configs:
      - names:
          - "_ceph-exporter._tcp.twop.ch"
        type: SRV
        refresh_interval: 30s
  - job_name: 'cadvisor-lxc'
    metrics_path: "/metrics"
    metric_relabel_configs:
      - source_labels: [ "id" ]
        regex: ".*lxc/([0-9]+).*"
        target_label: "lxc_id"
        replacement: "$1"
      - source_labels: [ "id" ]
        regex: ".*/system.slice/([^/]+)"
        target_label: "systemd_service"
        replacement: "$1"
    dns_sd_configs:
      - names:
          - "_cadvisor-lxc._tcp.twop.ch"
        type: SRV
        refresh_interval: 30s
  - job_name: 'cadvisor-docker'
    metrics_path: "/metrics"
    dns_sd_configs:
      - names:
          - "_cadvisor-docker._tcp.twop.ch"
        type: SRV
        refresh_interval: 30s
  - job_name: 'blackbox_http_srv'
    metrics_path: /probe
    params:
      module: [http_2xx]
    dns_sd_configs:
      - names:
          - "_blackbox-exporter._tcp.twop.ch"
        type: SRV
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        regex: (.*)
        replacement: https://$1
        target_label: __param_target