services:
  haproxy-sidecar:
    image: registry.gitlab.com/two-p/haproxy-traefik-sidecar:0.0.3
    environment:
      - "HAPROXY_SOCKET_TCP_ADDRESS=localhost:9999"
      - TRAEFIK_API_JSON={"http://192.168.0.111:8080/api/http/routers":"swarm_prod_traefik","http://192.168.1.51:8080/api/http/routers":"k3s_prod_traefik"}
      - "UPDATE_INTERVAL_IN_SECOND=60"
    network_mode: host