---
- name: Upload HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
- name: Upload HAProxy private map file
  template:
    src: private-hostnames.map
    dest: /etc/haproxy/private-hostnames.map
    owner: root
    group: root
    mode: '0644'
- name: Upload HAProxy public map file
  template:
    src: public-hostnames.map
    dest: /etc/haproxy/public-hostnames.map
    owner: root
    group: root
    mode: '0644'
- name: Reload HAProxy service
  service:
    name: haproxy
    state: reloaded
- name: Allow port
  ufw:
    rule: allow
    port: '5789'
    proto: tcp
