apiVersion: v2
name: cheap
description: A Helm chart for cheap app
type: application
version: 0.0.1

dependencies:
  - name: valkey
    version: "0.10.0"
    repository: "https://valkey.io/valkey-helm"
  - name: mysql
    version: "14.0.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled