environment: ""

version: ""

projectName: "cheap"
domain: ""
entrypoint: "web-private"
previewPrefix: ""

api:
  revisionHistoryLimit: 3
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

worker:
  revisionHistoryLimit: 3
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

webapp:
  revisionHistoryLimit: 3
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

mysql:
  enabled: false
  image:
    repository: bitnamilegacy/mysql
    tag: 9.4.0-debian-12-r1
  auth:
    rootPassword: "rootpassword"
    database: "cheap"
    username: "cheap"
    password: "cheappassword"
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m