environment: ""

version: ""

projectName: "cheap"
domain: ""
entrypoint: "web-private"
previewPrefix: ""

api:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

worker:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

valkey:
  auth:
    enabled: false

  master:
    persistence:
      enabled: true
      size: 8Gi

    resources:
      limits:
        memory: 256Mi
        cpu: 250m
      requests:
        memory: 128Mi
        cpu: 100m

  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 8Gi

    resources:
      limits:
        memory: 256Mi
        cpu: 250m
      requests:
        memory: 128Mi
        cpu: 100m

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      
mysql:
  enabled: false
  image:
    repository: bitnamilegacy/mysql
    tag: 9.4.0-debian-12-r1
  auth:
    rootPassword: "rootpassword"
    database: "cheap"
    username: "cheap"
    password: "cheappassword"
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m