environment: ""

version: ""

projectName: "navan"
domain: ""
entrypoint: "web-private"

webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

server:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G