services:
  monitoring:
    image: checkmk/check-mk-raw:2.4.0-latest
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8001:8000"
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/cephfs/checkmk/:/omd/sites:rw
    networks:
      - traefik_proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.checkmk.rule=Host(`checkmk.twop.ch`)"
        - "traefik.http.routers.checkmk.entrypoints=web-private"
        - "traefik.http.services.checkmk.loadbalancer.server.port=5000"
        - "homepage.group=Monitoring"
        - "homepage.name=checkmk"
        - "homepage.icon=https://avatars.githubusercontent.com/u/47812383?s=200&v=4"
        - "homepage.href=https://checkmk.twop.ch"
        - "homepage.description=checkmk"
networks:
  traefik_proxy:
    external: true