---
- hosts: k3s_dev
  become: yes
  vars:
    k3s_init_group: "init_dev"
    k3s_join_group: "join_dev"
    k3s_tls_san: "k3s.dev.twop.ch"
  roles:
    - common/package
    - k3s
    - users
    - node_exporter