---
- hosts: proxmox,proxmox_backup_server
  become: yes
  roles:
    - common/package
    - users
    - geerlingguy.docker
    - docker_post_setup
    - graphite_exporter
    - ceph_exporter
    - node_exporter