---
- hosts: haproxy_servers
  become: yes
  roles:
    - common/package
    - users
    - role: haproxy/main
      tags:
        - main

- hosts: proxmox21
  become: yes
  roles:
    - role: haproxy/nohan
      tags:
        - main

- hosts: nlb
  become: yes
  vars:
    keepalived_state: BACKUP
    keepalived_interface: eth0
    keepalived_virtual_router_id: 10
    keepalived_priority: 100
    keepalived_advert_int: 1
    keepalived_auth_type: PASS
    keepalived_auth_pass: 1234
    keepalived_virtual_ipaddress:
      - 192.168.1.246/16
      - 192.168.1.253/16
    certbot_domains:
      - "twop.ch"
      - "*.twop.ch"
      - "*.dev.twop.ch"
      - "*.staging.twop.ch"
      - "*.prod.twop.ch"
      - "*.test.twop.ch"
      - "*.k3s.prod.twop.ch"
      - "*.k3s.dev.twop.ch"
      - "*.k3s.test.twop.ch"
      - "*.k3s.staging.twop.ch"
  roles:
    - common/package
    - users
    - role: keepalived
      tags:
        - main
        - keepalived
    - role: haproxy/nlb
      tags:
        - main
    - role: certbot
      tags:
        - main
        - certbot
