---
- hosts: proxmox,proxmox_backup_server
  become: yes
  roles:
    - common/package
    - users
    - graphite_exporter
    - ceph_exporter
    - node_exporter
    - pve
- hosts: proxmox_backup_server
  become: yes
  roles:
    - common/package
    - users
    - graphite_exporter
    - node_exporter
    - pbs