---
- hosts: proxmox
  become: yes
  roles:
    - common/package
    - users
    - graphite_exporter
    - ceph_exporter
    - node_exporter
    - pve
    - cadvisor/lxc
- hosts: proxmox_backup_server
  become: yes
  roles:
    - common/package
    - users
    - node_exporter
    - pbs