---
- hosts: wireguards
  become: yes
  vars:
    wireguard_peers:
      - public_key: dZB4Wiq8WkiBtCxsLy1ZCIqOniqYZu+9Mupx61k4oS8=
        allowed_ips: 10.10.0.2/32
      - public_key: jw8oC8kOJMMA3r2alK5Sxj9DOVCoeK4o1A9LMWcegDI=
        allowed_ips: 10.10.0.3/32
      - public_key: zenF3pj4hjiMiCJeFVkTaGyR/q/H0cgUgPwtkqDZNSM=
        allowed_ips: 10.10.0.4/32
      - public_key: G6zoIJ97l6pKz2AHtc+6XQsPydQe/oz6n+QIcsA1PkQ=
        allowed_ips: 10.10.0.5/32
      - public_key: 0GWND9A18Xk4Q2dqgTOebju2p6QK+ZTVpHfYjc4e/T8=
        allowed_ips: 10.10.0.6/32
  roles:
    - common/package
    - users
    - role: wireguard
      tags:
        - main