services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.16
    ports:
      - "3001:3001"
    volumes:
      - data:/app/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.twop.ch`)"
        - "traefik.http.routers.uptimekuma.entrypoints=web-private"
        - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
        - "homepage.group=Monitoring"
        - "homepage.name=Uptimekuma"
        - "homepage.icon=https://uptimekuma.org/wp-content/uploads/2025/01/Uptime-Kuma-Logo.png"
        - "homepage.href=https://uptimekuma.twop.ch"
        - "homepage.description=Uptimekuma"
    restart: unless-stopped
    networks:
      - traefik_proxy
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.29,rw,nfsvers=4"
      device: ":/volume1/swarm01/uptimekuma/data"
networks:
  traefik_proxy:
    external: true