image: alpine:3.20.1

stages:
  - init
  - plan
  - apply  
  - deploy

variables:
  VERSION:
    description: "The docker image version"
  ENVIRONMENT:
    description: "The environment where to deploy (k8s namespace)"
  KUBECONFIG_CONTENT:
    description: "Kubeconfig file as base64"
  PROJECT:
    description: "Project name"

init_infra:
  stage: init
  script:
    - apk add --no-cache terraform
    - echo "$TF_BACKEND_HCL_INFRA" | base64 -d > terraform/infra/backend.hcl
    - cd terraform/infra
    - terraform init -backend-config=backend.hcl
  rules:
    - changes:
        - terraform/infra/**

plan_infra:
  stage: plan
  needs: [init_infra]
  script:
    - cd terraform/infra
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/infra/tfplan
    expire_in: 1 hour
  rules:
    - changes:
        - terraform/infra/**

apply_infra:
  stage: apply
  when: manual
  needs: [plan_infra]
  script:
    - cd terraform/infra
    - terraform apply -auto-approve tfplan
  rules:
    - changes:
        - terraform/infra/**

init_plateform:
  stage: init
  script:
    - apk add --no-cache terraform
    - echo "$TF_BACKEND_HCL_PLATEFORM" | base64 -d > terraform/plateform/backend.hcl
    - cd terraform/plateform
    - terraform init -backend-config=backend.hcl
  rules:
    - changes:
        - terraform/plateform/**

plan_plateform:
  stage: plan
  needs: [init_plateform]
  script:
    - cd terraform/plateform
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/plateform/tfplan
    expire_in: 1 hour
  rules:
    - changes:
        - terraform/plateform/**

apply_plateform:
  stage: apply
  when: manual
  needs: [plan_plateform]
  script:
    - cd terraform/plateform
    - terraform apply -auto-approve tfplan
  rules:
    - changes:
        - terraform/plateform/**
deploy-chart:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: always
    - when: never
  script:
    - apk add --no-cache helm --repository http://dl-3.alpinelinux.org/alpine/edge/community/ yq
    - echo $KUBECONFIG_CONTENT | base64 -d > kubeconfig.yml
    - chmod 600 kubeconfig.yml
    - export KUBECONFIG=./kubeconfig.yml
    - |-
      tee cicd-values.yaml <<EOF
      version: "$VERSION"
      EOF
    - yq '. *= load("cicd-values.yaml")' ./k8s/$PROJECT/$PROJECT.$ENVIRONMENT.values.yaml > values.yaml
    - yq -i ".appVersion = \"$VERSION\"" ./charts/$PROJECT/Chart.yaml
    - helm upgrade --install $PROJECT-$ENVIRONMENT ./charts/$PROJECT/ --values=values.yaml -n $PROJECT