image: alpine:3.20.1

stages:
  - deploy

variables:
  VERSION:
    description: "The docker image version"
  ENVIRONMENT:
    description: "The enviorment where to deploy (k8s namespace)"
  KUBECONFIG_CONTENT:
    description: "Kubeconfig file as base64"
deploy-timer-chart:
  stage: deploy
  script:
    - apk add --no-cache helm --repository http://dl-3.alpinelinux.org/alpine/edge/community/ yq
    - echo $KUBECONFIG_CONTENT | base64 -d > kubeconfig.yml
    - chmod 600 kubeconfig.yml
    - export KUBECONFIG=./kubeconfig.yml
    - |-
      tee cicd-values.yaml <<EOF
      version: "$VERSION"
      EOF
    - yq '. *= load("cicd-values.yaml")' ./k8s/timer/timer.$ENVIRONMENT.values.yaml > values.yaml
    - yq -i ".appVersion = \"$VERSION\"" ./charts/timer/Chart.yaml
    - helm upgrade --install timer ./charts/timer/ --values=values.yaml -n timer