image: alpine:3.18

stages:
  - validate
  - plan
  - apply  
  - deploy
  - ansible

.install_vault: &install_vault
  - apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ terraform curl unzip jq
  - curl -fsSL https://releases.hashicorp.com/vault/1.21.1/vault_1.21.1_linux_amd64.zip -o vault.zip
  - unzip vault.zip
  - mv vault /usr/local/bin/
  - vault login -no-print $(vault write -field=token auth/approle/gitlab_repo/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID)

.install_terraform: &install_terraform
  - apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ terraform curl unzip jq

.get_vault_secrets: &get_vault_secrets
  - ./.ci/retrieve_secrets.sh homelab

.default_terraform_setup_infra: &terraform_setup_infra
  - cd terraform/infra
  - terraform init -backend-config=backend-config.json
  - apk add --no-cache openssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

.default_terraform_setup_plateform: &terraform_setup_plateform
  - cd terraform/platform
  - terraform init -backend-config=backend-config.json
  - mkdir -p ~/.kube
  - echo $KUBECONFIG_CONTENT | base64 -d > ~/.kube/config

validate_infra:
  stage: validate
  before_script:
    - *install_vault
    - *install_terraform
    - *get_vault_secrets
    - *terraform_setup_infra
  script:
    - terraform validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - terraform/infra/**

plan_infra:
  stage: plan
  needs: [validate_infra]
  before_script:
    - *install_vault
    - *install_terraform
    - *get_vault_secrets
    - *terraform_setup_infra
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/infra/tfplan
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - terraform/infra/**

apply_infra:
  stage: apply
  when: manual
  needs: [plan_infra]
  before_script:
    - *install_vault
    - *install_terraform
    - *get_vault_secrets
    - *terraform_setup_infra
  script:
    - terraform apply -auto-approve tfplan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - terraform/infra/**

validate_platform:
  stage: validate
  before_script:
    - *install_vault
    - *install_terraform
    - *get_vault_secrets
    - *terraform_setup_plateform
  script:
    - terraform validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - terraform/platform/**

plan_platform:
  stage: plan
  needs: [validate_platform]
  before_script:
    - *install_vault
    - *install_terraform
    - *get_vault_secrets
    - *terraform_setup_plateform
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform/platform/tfplan
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - terraform/platform/**

apply_platform:
  stage: apply
  when: manual
  needs: [plan_platform]
  before_script:
    - *install_vault
    - *install_terraform
    - *get_vault_secrets
    - *terraform_setup_plateform
  script:
    - terraform apply -auto-approve tfplan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - terraform/platform/**

deploy-chart:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
      when: always
    - when: never
  before_script:
    - apk add --no-cache helm --repository http://dl-3.alpinelinux.org/alpine/edge/community/ yq
    - echo $KUBECONFIG_CONTENT | base64 -d > kubeconfig.yml
    - chmod 600 kubeconfig.yml
    - export KUBECONFIG=./kubeconfig.yml
    - |-
      tee cicd-values.yaml <<EOF
      version: "$VERSION"
      EOF
  script:
    - yq '. *= load("cicd-values.yaml")' ./k8s/$PROJECT/$PROJECT.$ENVIRONMENT.values.yaml > values.yaml
    - yq -i ".appVersion = \"$VERSION\"" ./charts/$PROJECT/Chart.yaml
    - helm upgrade --install $PROJECT-$ENVIRONMENT ./charts/$PROJECT/ --values=values.yaml -n $PROJECT

deploy-ansible:
  stage: ansible
  before_script:
    - apk add jq yq python3 py3-pip openssh --repository http://dl-3.alpinelinux.org/alpine/edge/community/ terraform
    - pip install ansible
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    - cd terraform/infra
    - echo "$TF_BACKEND_HCL_INFRA" | base64 -d > backend-config.json
    - terraform init -backend-config=backend-config.json
    - cd ../../ansible
    - sh generate_inventory.sh
    - chmod o-w .
  script:
    - ansible-playbook playbooks/site-homelab.yaml -i inventory/inventory.yaml
  needs:
    - job: apply_infra
      optional: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ansible/**/*
    - if: '$CI_JOB_STATUS == "success"'
      needs:
        - apply_infra
    - when: never
