apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: audiobookshelf-media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: audiobookshelf-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
  namespace: audiobookshelf
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: audiobookshelf-metadata-pv