services:
  nextcloud:
    image: nextcloud:31.0.2-apache
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.rule=Host(`nxtcld.twop.ch`)"
        - "traefik.http.routers.nextcloud.entrypoints=web"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
        - "homepage.group=Media"
        - "homepage.name=NextCloud"
        - "homepage.icon=https://nextcloud.com/c/uploads/2023/02/logo_nextcloud_white.svg"
        - "homepage.href=https://nxtcld.twop.ch"
        - "homepage.description=NextCloud"
    restart: unless-stopped
    volumes:
      - /mnt/cephfs/nextcloud:/var/www/html

    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true