global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'proxmox_graphite_exporter'
    metrics_path: "/metrics"
    static_configs:
      - targets:
        - "proxmox11.twop.ch:9108"
        - "proxmox12.twop.ch:9108"
        - "proxmox13.twop.ch:9108"
        - "proxmox21.twop.ch:9108"

  - job_name: 'proxmox_node_exporter'
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "proxmox11.twop.ch:9100"
          - "proxmox12.twop.ch:9100"
          - "proxmox13.twop.ch:9100"
          - "proxmox21.twop.ch:9100"