all:
  children:
    dns:
      hosts:
        proxy1:
          ansible_host: 192.168.0.20
          ansible_user: root
          ansible_port: 5789

    haproxy_servers:
      hosts:
        proxy1:
          ansible_host: 192.168.0.20
          ansible_user: root
          ansible_port: 5789

    docker:
      hosts:
        srv3:
          ansible_host: 192.168.0.30
          ansible_user: ubuntu

    proxmox:
      hosts:
        proxmox01:
          ansible_host: 192.168.0.211
          ansible_user: root
        proxmox02:
          ansible_host: 192.168.0.212
          ansible_user: root
        proxmox03:
          ansible_host: 192.168.0.213
          ansible_user: root

    k3s_prod:
      hosts:
        k3s-01.prod:
          ansible_host: 192.168.1.51
          ansible_user: ubuntu
        k3s-02.prod:
          ansible_host: 192.168.1.52
          ansible_user: ubuntu
        k3s-03.prod:
          ansible_host: 192.168.1.53
          ansible_user: ubuntu

    k3s_tmp:
      hosts:
        k3s-01.tmp:
          ansible_host: 192.168.1.61
          ansible_user: ubuntu
        k3s-02.tmp:
          ansible_host: 192.168.1.62
          ansible_user: ubuntu
        k3s-03.tmp:
          ansible_host: 192.168.1.63
          ansible_user: ubuntu

    swarm:
      hosts:
        swarm-01.prod:
          ansible_host: 192.168.0.111
          ansible_user: ubuntu
        swarm-02.prod:
          ansible_host: 192.168.0.112
          ansible_user: ubuntu
        swarm-03.prod:
          ansible_host: 192.168.0.113
          ansible_user: ubuntu

    database:
      hosts:
        database.prod:
          ansible_host: 192.168.1.110
          ansible_user: root