apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    listener "tcp" {
      address     = "0.0.0.0:8400"
      tls_disable = 1
    }
    
    storage "mysql" {
      address  = "database.prod.twop.ch:3306"
      username = "vault"
      password = "UbG9-:bKZXP@CiNO"
      database = "vault"
    }
    
    ui = true