services:
  haproxy-sidecar:
    image: registry.gitlab.com/two-p/haproxy-traefik-sidecar:0.0.2
    environment:
      - "HAPROXY_SOCKET_TCP_ADDRESS=192.168.0.20:9999"
      - "MAP_FILE_NAME=public-hostnames.map"
      - TRAEFIK_API_JSON={"http://192.168.0.111:8080/api/http/routers":"swarm_prod_traefik","http://traefik.k8s.twop.ch/api/http/routers":"k3s_prod_traefik"}
      - "UPDATE_INTERVAL_IN_SECOND=60"
    volumes:
      - "/etc/haproxy/public-hostnames.map:/app/public-hostnames.map"