---
- name: Install HAProxy package
  package:
    name: haproxy
    state: present

- name: Allow HTTP port (80)
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS port (443)
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow HAProxy stats port (8404)
  ufw:
    rule: allow
    port: '8404'
    proto: tcp

- name: Allow HAProxy metrics port (8405)
  ufw:
    rule: allow
    port: '8405'
    proto: tcp

- name: Upload HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Restart HAProxy service
  service:
    name: haproxy
    state: reloaded

