---
- name: Ensure users are created and has a public key
  hosts: docker
  become: yes
  vars:
    users:
      - dpage
  tasks:
    - name: Create user {{ item }}
      loop: {{ users }}
      user:
        name: {{ item }}
        state: present
        shell: /bin/bash

    - name: Create .ssh directory
      loop: {{ users }}
      file:
        path: /home/{{ item }}/.ssh
        state: directory
        owner: {{ item }}
        group: {{ item }}
        mode: '0700'

    - name: Add public key to {{ item }}'s authorized_keys
      authorized_key:
        user: {{ item }}
        state: present
        key: "{{ lookup('file', '~/.ssh/private.pub') }}"

    - name: Ensure proper permissions for authorized_keys
      file:
        path: /home/{{ item }}/.ssh/authorized_keys
        owner: {{ item }}
        group: {{ item }}
        mode: '0600'
    - name: Add {{ item }} to sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ item }} ALL='
        line: '{{ item }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
- name: Install docker
  hosts: docker
  remote_user: root
  tasks:
    - name: Upgrade the OS
      apt:
        upgrade: full
        autoclean: true
        autoremove: true
    - name: Install git
      apt:
        name: git
        update_cache: yes
    - name: Install docker dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - wget
          - unzip
          - gnupg
          - gpg
          - lsb-release
        update_cache: yes
    - name: Set up the docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update
    - name: Install Docker Engine
      apt:
        update_cache: yes
        autoclean: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Add current user to docker group
      user:
        name: ubuntu
        group: docker
    - name: Add current user to docker group
      user:
        name: {{ item }}
        group: docker
    - name: Install NFS client package
      package:
        name: nfs-common
        state: present

    - name: Create mount point directory
      file:
        path: "/mnt/dpage"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Mount NFS share
      mount:
        src: "ddpnas1.home:/volume1/dpage"
        path: "/mnt/dpage"
        fstype: nfs
        state: mounted
        opts: rw

    - name: Ensure NFS share is mounted on boot
      mount:
        src: "ddpnas1.home:/volume1/dpage"
        path: "/mnt/dpage"
        fstype: nfs
        opts: defaults
        state: present