services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "9192:8080"
    volumes:
      # Host filesystem (read-only)
      - /:/rootfs:ro

      # Docker-related paths
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

      # Cgroups
      - /sys/fs/cgroup:/sys/fs/cgroup:ro