services:
  traefik:
    image: traefik:v3.5.1
    command:
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.swarm.watch=true"
#      - "--providers.kubernetesingress=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-private.address=:81"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=TRACE"
      - "--providers.swarm.network=traefik_proxy"

    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.twop.ch`)"
        - "traefik.http.routers.traefik.entrypoints=web-private"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == manager
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
    attachable: true