---
- name: Get worker join token from manager
  delegate_to: "{{ groups[swarm_manager_group][0] }}"
  shell: docker swarm join-token -q worker
  register: worker_token
  run_once: true

- name: Join Docker Swarm as worker
  shell: >
    docker swarm join --token {{ worker_token.stdout }} {{ hostvars[groups[swarm_manager_group][0]].ansible_host }}:2377
  args:
    creates: /var/lib/docker/.swarm_initialized

- name: Set swarm_initialized file
  shell: >
    touch /var/lib/docker/.swarm_initialized
  args:
    creates: /var/lib/docker/.swarm_initialized