services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.28.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.audio.rule=Host(`audio.twop.ch`)"
        - "traefik.http.routers.audio.entrypoints=web"
        - "traefik.http.services.audio.loadbalancer.server.port=80"
        - "homepage.group=Media"
        - "homepage.name=Audiobookshelf"
        - "homepage.icon=https://www.audiobookshelf.org/Logo.png"
        - "homepage.href=https://audio.twop.ch"
        - "homepage.description=Audiobookshelf"
    ports:
      - "13378:80"
    restart: unless-stopped
    volumes:
      - media:/audiobooks:ro
      - config:/config
      - metadata:/metadata
    environment:
      - TZ=Europe/Zurich
    networks:
      - traefik_proxy

volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.29,rw,nfsvers=4"
      device: ":/volume1/dpage"

  config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.29,rw,nfsvers=4"
      device: ":/volume1/swarm01/audiobookshelf/config"

  metadata:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.29,rw,nfsvers=4"
      device: ":/volume1/swarm01/audiobookshelf/metadata"

networks:
  traefik_proxy:
    external: true