---
- name: Ensure UFW is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow ports through UFW
  ansible.builtin.command: ufw allow {{ item }}
  loop: "{{ ufw_ports }}"
  notify: Reload UFW

- name: Enable UFW
  ansible.builtin.command: ufw --force enable

- name: Ensure UFW status is active
  ansible.builtin.command: ufw status verbose
  register: ufw_status
  changed_when: false
