services:
  vault:
    image: hashicorp/vault:1.20
    configs:
      - source: vault_config
        target: /vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vault.rule=Host(`vault.twop.ch`)"
        - "traefik.http.routers.vault.entrypoints=web"
        - "traefik.http.services.vault.loadbalancer.server.port=8300"
    networks:
      - traefik_proxy
configs:
  vault_config:
    file: ./config.hcl

networks:
  traefik_proxy:
    external: true