services:
  autodel:
    image: registry.gitlab.com/didierpage/tvtyggdl/auto-del:dev
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.autodel.rule=Host(`autodel.twop.ch`)"
        - "traefik.http.routers.autodel.entrypoints=web"
        - "traefik.http.services.autodel.loadbalancer.server.port=80"
    env_file:
      - .autodel.env
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true