- name: Install common packages
  ansible.builtin.package:
    name:
      - ufw
      - git
      - logrotate
      - rsyslog
      - unzip
      - curl
      - tree
      - fail2ban
    state: present