- name: Install common packages
  ansible.builtin.package:
    name:
      - ufw
      - git
      - logrotate
      - rsyslog
      - unzip
      - curl
      - tree
      - fail2ban
    state: present

- name: Allow HTTP port (22)
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
