---
- name: Generate K3s token on the first manager node
  set_fact:
    k3s_token: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

- name: Share K3s token with all nodes
  set_fact:
    k3s_token: "{{ hostvars[groups[k3s_init_group][0]]['k3s_token'] }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ ansible_play_hosts }}"

- name: Install K3s on the first manager node
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_TOKEN={{ k3s_token }} \
    sh -s - server \
      --cluster-init \
      --tls-san {{ k3s_tls_san }}
  args:
    creates: /usr/local/bin/k3s

- name: Read K3s kubeconfig from first manager node
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  delegate_to: "{{ groups[k3s_init_group][0] }}"
  register: k3s_kubeconfig_raw
  run_once: true

- name: Upload kubeconfig to Vault using HTTP API (KV v2)
  uri:
    url: "{{ vault_addr }}/v1/kubernetes/data/{{ k3s_tls_san }}"
    method: POST
    headers:
      "X-Vault-Token": "{{ vault_token }}"
      "Content-Type": "application/json"
    body_format: json
    body:
      data:
        kubeconfig: "{{ k3s_kubeconfig_raw }}"
    status_code:
      - 200
      - 204
  delegate_to: localhost
  become: false
  run_once: true
