---
- name: Get K3s token from manager
  set_fact:
    k3s_token: "{{ hostvars[groups[k3s_init_group][0]]['k3s_token'] }}"

- name: Install K3s on worker and join cluster
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_TOKEN={{ k3s_token }} \
    sh -s - agent \
      --server https://{{ hostvars[groups[k3s_init_group][0]].ansible_default_ipv4.address }}:6443
  args:
    creates: /usr/local/bin/k3s