---
- name: Get K3s token from manager
  set_fact:
    k3s_token: "{{ hostvars[groups[k3s_init_group][0]]['k3s_token'] }}"

- name: Install K3s on worker and join cluster
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_TOKEN={{ k3s_token }} \
    sh -s - server \
      --server https://{{ hostvars[groups[k3s_init_group][0]].ansible_default_ipv4.address }}:6443 \
      --tls-san {{ k3s_tls_san }} \
      {% if k3s_disable_servicelb | default(false) %}--disable servicelb{% endif %} \
      {% if k3s_disable_traefik | default(false) %}--disable traefik{% endif %}

  args:
    creates: /usr/local/bin/k3s