- import_playbook: servers/k3s.yaml
- import_playbook: servers/proxies.yaml
- import_playbook: servers/proxmox.yaml
- import_playbook: servers/swarm.yaml
- import_playbook: servers/glrunner.yaml
- import_playbook: servers/wireguards.yaml
- import_playbook: servers/vps.yaml