apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-html-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany   # Use ReadWriteMany if nginx should write files
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # IMPORTANT
  nfs:
    server: 192.168.0.92
    path: /mnt/main/k3s_dev/nfs