apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-html-pvc
  namespace: nfs
spec:
  storageClassName: ""   # ⬅ disables local-path
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi