---
dependencies:
  - role: ufw
    vars:
      ufw_ports:
        - '6443'
        - '8472'
        - '51820'
        - '2379'
        - '2380'
        - '10250'
        - '51820'
        - '51821'
        - '5001'