---
- name: Ensure dirmngr and gnupg are installed
  apt:
    name:
      - dirmngr
      - gnupg
    state: present
    update_cache: yes

- name: Enable non-local bind in sysctl
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes

- name: Add HAProxy PPA repository
  apt_repository:
    repo: ppa:vbernat/haproxy-3.2
    state: present

- name: Install HAProxy 3.2
  apt:
    name: haproxy=3.2.*
    state: present
    update_cache: yes

- name: Start HAProxy service
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Upload HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Reload HAProxy service
  service:
    name: haproxy
    state: reloaded
  ignore_errors: true

- name: Create application directory
  file:
    path: "/opt/haproxy-traefik-sidecar"
    state: directory
    mode: '0755'

- name: Copy Docker Compose file
  template:
    src: compose.yml
    dest: "/opt/haproxy-traefik-sidecar/compose.yml"
    mode: '0644'

- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/haproxy-traefik-sidecar"
    files:
      - compose.yml
    state: present



