services:
  graphite-exporter:
    image: prom/graphite-exporter:v0.16.0
    restart: unless-stopped
    ports:
      - "9109:9109/udp"
    volumes:
      - "./mapping.yml:/tmp/mapping.yml"
    command:
      - "--graphite.mapping-config=/tmp/mapping.yml"
  graphite-relabler:
    image: registry.gitlab.com/two-p/graphite-proxmox-relabler:0.0.2
    restart: unless-stopped
    ports:
      - "9108:9108"
    volumes:
      - "/etc/pve:/data:ro"
    command:
      - "--graphiteExporterUrl=http://graphite-exporter:9108/metrics"
      - "--folder=/data"
      - "--port=9108"