apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
  namespace: plex
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.29
    path: /volume1/dpage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  namespace: plex
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.92
    path: /mnt/main/k3s_prod/plex/config
