domain: cheap.twop.ch
environment: prod

version: deacdab8

api:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G
webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G