domain: cheap.twop.ch
environment: prod
version: 82a1c4cc
api:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G
worker:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G
webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G
