apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-webapp-service-{{ .Values.environment }}
spec:
  selector:
    app: {{ .Chart.Name }}-webapp-{{ .Values.environment }}
  type: ClusterIP
  ports:
    - name: svc-webapp-port
      port: 80
      targetPort: webapp-port