domain: navan.staging.twop.ch
environment: staging
# Will be replaced in the ci
#version: <short hash>-staging
webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G
server:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G