apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptimekuma-data-pv
  namespace: uptimekuma
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.0.92
    path: /mnt/main/k3s_prod/uptimekuma/data
