apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-data-pvc
  namespace: uptimekuma
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: uptimekuma-data-pv