apiVersion: v1
kind: Service
metadata:
  namespace: uptimekuma
  name: uptimekuma
  labels:
    app: uptimekuma
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: uptimekuma