---
dependencies:
  - role: ufw
    vars:
      ufw_ports:
        - '8006'
        - '5900:5999/tcp'
        - '3128'
        - '22'
        - '111'
        - '25'
        - '5404:5412/udp'
        - '60000:60050/tcp'

