---
dependencies:
  - role: ufw
    vars:
      ufw_ports:
        - '22'
        - '8006'
        - '5404:5405/udp'
        - '5900:5999/tcp'
        - '10000:10099/tcp'
        - '2049'
        - '3260'
        - '8007'

