domain: navan.twop.ch
environment: prod
# Will be replaced in the ci
#version: <short hash>
webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G
server:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G