---
- name: Create application directory
  file:
    path: "/opt/ceph_exporter"
    state: directory
    mode: '0755'

- name: Copy Docker Compose file
  template:
    src: compose.yml
    dest: "/opt/ceph_exporter/compose.yml"
    mode: '0644'

- name: Restart Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/ceph_exporter"
    files:
      - compose.yml
    state: present