domain: timer.dev.twop.ch
environment: dev
# Will be replaced in the ci
version: ad19286c-dev

webapp:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G

api:
  replicas: 1
  resources:
    memory:
      limit: 1G
      request: 1G