apiVersion: v1
kind: Service
metadata:
  namespace: audiobookshelf
  name: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  type: ClusterIP
  ports:
    - name: service-port
      port: 80
      targetPort: app-port
      protocol: TCP
  selector:
    app: audiobookshelf